version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    environment:
      RABBITMQ_CONFIG_FILE: "/etc/rabbitmq/conf.d/rabbit.conf"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ../config/rabbitmq/rabbit.conf/:/etc/rabbitmq/conf.d/rabbit.conf
      