version: '3'
services:
  influx: 
    container_name: influxdb
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      INFLUX_USER: "testuser"
      INFLUX_PASSWORD: "testpw"
    volumes:
      - "../config/influxdb/influx.conf:/etc/influxdb/influxdb.conf"
      - "../data/influxdb/:/var/lib/influxdb/data"