version: '3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - "../plugin/grafana/:/var/lib//grafana/plugins/"
      - ../config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../data/grafana/:/var/lib/grafana
